/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package lab_1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String arg[]){
    	Library lib = new LIbrary(); 
    	if (lib.someLibraryMethod())
    		System.out.println("When there is fire, commit and push.");
    }
}
